<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 *
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Needle;

use Zikula\PagesModule\Needle\Base\AbstractPageNeedle;

/**
 * PageNeedle implementation class.
 */
class PageNeedle extends AbstractPageNeedle
{
    // feel free to extend the needle here
}
