
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/src/extensions/Zikula/PagesModule/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
