services:

    app.tokens.action_listener:
        class: Zikula\PagesModule\Listener\AdminAuthListener
        arguments: ['@zikula_permissions_module.api.permission']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    zikula_pages_module.link_container:
        class: Zikula\PagesModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@router"
          - "@zikula_permissions_module.api.permission"
          - "@=service('zikula_extensions_module.api.variable').get('ZikulaPagesModule', 'enablecategorization', true)"
        tags:
          - { name: zikula.link_container }

    zikula_pages_module.helper.search_helper:
        class: Zikula\PagesModule\Helper\SearchHelper
        arguments:
          - '@zikula_permissions_module.api.permission'
          - '@doctrine.orm.entity_manager'
          - '@zikula_categories_module.api.category_permission'
          - '@session'
          - "@=service('zikula_extensions_module.api.variable').get('ZikulaPagesModule', 'enablecategorization', true)"
        tags:
            - { name: zikula.searchable_module, bundleName: ZikulaPagesModule}

    zikula_pages_module.hook_subscriber.ui_hooks_subscriber:
        class: Zikula\PagesModule\HookSubscriber\UiHooksSubscriber
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: "subscriber.pages.ui_hooks.pages" }

    zikula_pages_module.hook_subscriber.filter_hooks_subscriber:
        class: Zikula\PagesModule\HookSubscriber\FilterHooksSubscriber
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: "subscriber.pages.filter_hooks.pagesfilter" }

    zikula_pages_module.hook_subscriber.form_aware_hook_subscriber:
        class: Zikula\PagesModule\HookSubscriber\FormAwareHookSubscriber
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: "subscriber.pages.form_aware_hook.pages" }
