<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Entity\Factory\Base;

use Symfony\Component\HttpFoundation\RequestStack;
use Zikula\PagesModule\Entity\PageEntity;
use Zikula\PagesModule\Helper\PermissionHelper;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * @var RequestStack
     */
    protected $requestStack;

    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    public function __construct(
        RequestStack $requestStack,
        PermissionHelper $permissionHelper
    ) {
        $this->requestStack = $requestStack;
        $this->permissionHelper = $permissionHelper;
    }

    /**
     * Initialises a given page instance.
     */
    public function initPage(PageEntity $entity): PageEntity
    {
        $entity->setPageLanguage($this->requestStack->getCurrentRequest()->getLocale());

        return $entity;
    }
}
