<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Form\Type;

use Zikula\PagesModule\Form\Type\Base\AbstractPageType;

/**
 * Page editing form type implementation class.
 */
class PageType extends AbstractPageType
{
    // feel free to extend the page editing form type class here
}
