<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Listener;

use Zikula\PagesModule\Listener\Base\AbstractInstallerListener;

/**
 * Event handler implementation class for extension installer events.
 */
class InstallerListener extends AbstractInstallerListener
{
    // feel free to enhance the parent methods
}
