<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Form\Type\QuickNavigation;

use Zikula\PagesModule\Form\Type\QuickNavigation\Base\AbstractPageQuickNavType;

/**
 * Page quick navigation form type implementation class.
 */
class PageQuickNavType extends AbstractPageQuickNavType
{
    // feel free to extend the base form type class here
}
