<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule;

use Zikula\PagesModule\Base\AbstractAppSettings;

/**
 * Application settings class for handling module variables.
 */
class AppSettings extends AbstractAppSettings
{
    // feel free to add your own methods here
}
