<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Helper;

use Zikula\PagesModule\Helper\Base\AbstractEntityDisplayHelper;

/**
 * Entity display helper implementation class.
 */
class EntityDisplayHelper extends AbstractEntityDisplayHelper
{
    // feel free to extend the entity display helper here
}
