<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 *
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Helper\Base;

use Gedmo\Sluggable\Util\Urlizer;

/**
 * Custom slug transliterator for proper handling of umlauts and accents during permalink generation.
 *
 * @see https://github.com/Atlantic18/DoctrineExtensions/pull/1504
 */
abstract class AbstractSlugTransliterator
{
    /**
     * Transliterates a given text.
     */
    public static function transliterate($text, $separator = '-'): string
    {
        $text = Urlizer::unaccent($text);

        return Urlizer::urlize($text, $separator);
    }
}
