<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Entity\Factory;

use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use Zikula\PagesModule\Entity\Factory\Base\AbstractEntityInitialiser;
use Zikula\PagesModule\Entity\PageEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
class EntityInitialiser extends AbstractEntityInitialiser
{
    /**
     * @var VariableApiInterface
     */
    private $variableApi;

    public function initPage(PageEntity $entity): PageEntity
    {
        parent::initPage($entity);

        $entity->setDisplayWrapper($variableApi->get('ZikulaPagesModule', 'displayWrapper', true));
        $entity->setDisplayTitle($variableApi->get('ZikulaPagesModule', 'displayTitle', true));
        $entity->setDisplayCreated($variableApi->get('ZikulaPagesModule', 'displayCreated', true));
        $entity->setDisplayUpdated($variableApi->get('ZikulaPagesModule', 'displayUpdated', true));
        $entity->setDisplayTextInfo($variableApi->get('ZikulaPagesModule', 'displayTextInfo', true));
        $entity->setDisplayPrint($variableApi->get('ZikulaPagesModule', 'displayPrint', true));

        return $entity;
    }

    /**
     * @required
     */
    public function setVariableApi(VariableApiInterface $variableApi): void
    {
        $this->variableApi = $variableApi;
    }
}
