<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Entity\Factory;

use Zikula\PagesModule\Entity\Factory\Base\AbstractEntityFactory;

/**
 * Factory class used to create entities and receive entity repositories.
 */
class EntityFactory extends AbstractEntityFactory
{
    // feel free to customise the factory
}
