<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Form\Type\Finder;

use Zikula\PagesModule\Form\Type\Finder\Base\AbstractPageFinderType;

/**
 * Page finder form type implementation class.
 */
class PageFinderType extends AbstractPageFinderType
{
    // feel free to extend the base form type class here
}
