<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 *
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\Twig\Base;

use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;
use Twig\TwigFunction;
use Zikula\PagesModule\Twig\TwigRuntime;

/**
 * Twig extension base class.
 */
abstract class AbstractTwigExtension extends AbstractExtension
{
    public function getFunctions()
    {
        return [
            new TwigFunction('zikulapagesmodule_increaseCounter', [TwigRuntime::class, 'increaseCounter']),
            new TwigFunction('zikulapagesmodule_objectTypeSelector', [TwigRuntime::class, 'getObjectTypeSelector']),
            new TwigFunction('zikulapagesmodule_templateSelector', [TwigRuntime::class, 'getTemplateSelector']),
        ];
    }
    
    public function getFilters()
    {
        return [
            new TwigFilter('zikulapagesmodule_listEntry', [TwigRuntime::class, 'getListEntry']),
            new TwigFilter('zikulapagesmodule_formattedTitle', [TwigRuntime::class, 'getFormattedEntityTitle']),
            new TwigFilter('zikulapagesmodule_objectState', [TwigRuntime::class, 'getObjectState'], ['is_safe' => ['html']]),
        ];
    }
}
