<?php

/**
 * Pages.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 *
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\PagesModule\HookSubscriber;

use Zikula\PagesModule\HookSubscriber\Base\AbstractPageUiHooksSubscriber;

/**
 * Implementation class for ui hooks subscriber.
 */
class PageUiHooksSubscriber extends AbstractPageUiHooksSubscriber
{
    // feel free to add your own convenience methods here
}
